[book]
authors = ["Metal³ community"]
language = "en"
multilingual = false
src = "src"
title = "Metal³ user-guide"

[preprocessor.releasetags]

[output.html]
git-repository-url = "https://github.com/metal3-io/"
curly-quotes = true
