[book]
authors = ["The Metal³ Community"]
language = "en"
multilingual = false
src = "src"
title = "Metal³ user-guide"

[output.html]
git-repository-url = "https://github.com/metal3-io"
curly-quotes = true